import Head from "next/head";
import { Inter } from "next/font/google";
import Footer from "@/components/common/Footer";
import Menu from "../restaurant/menu/_components/our-takeout-menu";
export default function Root() {
  // const [index, setIndex] = useState(1);
  return (
    <>
      <Head>
        <title>Checkout - Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="BillingWrapperCenter">
        <Links index={index} setIndex={setIndex} />
        {index === 0 && <Billingindex />}
        {index === 1 && <PaymentIndex />}
      </div> */}
      <Menu />
      <Footer />
    </>
  );
}
